apiVersion: v1
kind: Secret
metadata:
  name: ea-league-secrets
type: Opaque
stringData:
  # Replace with actual base64 encoded secrets or use a secrets manager in prod
  DATABASE_URL: "postgresql://postgres.xxx:xxx@aws-0-eu-central-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
  DIRECT_URL: "postgresql://postgres.xxx:xxx@aws-0-eu-central-1.pooler.supabase.com:5432/postgres"
